apiVersion: apigw.opentelekomcloud.m.crossplane.io/v1alpha1
kind: EnvironmentV2
metadata:
  annotations:
    meta.upbound.io/example-id: apigw/v1alpha1/environmentv2
  labels:
    testing.upbound.io/example-name: test
  name: test
  namespace: upbound-system
spec:
  forProvider:
    description: ${var.description}
    instanceId: ${var.instance_id}
    name: ${var.environment_name}
